#include "Gouvernement\remoteExec.cpp"
#include "Entreprise\remoteExec.cpp"
#include "WhitelistMenu\remoteExec.cpp"
#include "Interpol\remoteExec.cpp"
#include "Restrain\remoteExec.cpp"
#include "Mining\remoteExec.cpp" 